Added Japanese translation
Utazukin/Ichaival pull request #36
Opened 2022-05-06 13:20 UTC by kuragehimekurara1

Added Japanese translation. Please confirm it is.

2022-05-09 22:47 UTC, Utazukin requested changes
Looks pretty good.  There are just a couple small issues.  Plus a couple strings that I had marked as untranslatable by mistake.

2022-05-09 22:47 UTC, Utazukin commented on app/src/main/res/values-ja/strings.xml
> +        <item>@string/ダークテーマ</item>
These should be the name of the string, not the translations, i.e. @string/dark_theme.

2022-05-09 22:47 UTC, Utazukin commented on app/src/main/res/values-ja/strings.xml
> +        <item>@string/ブラックテーマ</item>
Same for this.

2022-05-09 22:47 UTC, Utazukin commented on app/src/main/res/values-ja/strings.xml
> +    <string name="rtol_pref_name" translatable="false">Right to Left Reader</string>
This one was my mistake.  It is translatable.  I've updated the original strings.xml to show this.

2022-05-09 22:47 UTC, Utazukin commented on app/src/main/res/values-ja/strings.xml
> +    <string name="license_key" translatable="false">ライセンス</string>
This shouldn't be translated since it is used as the key to access the setting, and isn't displayed to the user.

2022-05-09 22:47 UTC, Utazukin commented on app/src/main/res/values-ja/strings.xml
> +    <string name="search_delay_pref" translatable="false">Search Delay</string>
This was another one that I marked as untranslatable by mistake.

2022-05-10 14:39 UTC, kuragehimekurara1 commented
Excuse me. I will fix the Japanese translation soon.

2022-05-10 14:52 UTC, kuragehimekurara1 commented
Fixed some translations. How about this?

2022-05-10 22:25 UTC, Utazukin approved these changes

2022-05-10 22:29 UTC, merged